var chokidar = require("chokidar"),
    isArray = require("@nathanfaucett/is_array"),
    isFunction = require("@nathanfaucett/is_function"),
    emptyFunction = require("@nathanfaucett/empty_function"),
    isNullOrUndefined = require("@nathanfaucett/is_null_or_undefined");


module.exports = watch;


function watch(glob, options, task) {
    var watcher, fn;

    if (isFunction(options)) {
        task = options;
        options = {};
    }
    if (!isFunction(task) || isArray(task)) {
        throw new Error(
            "watching " + glob + ": watch task has to be " +
            "a function or generated by using task.parallel " +
            "or task.series"
        );
    }

    options = options || {};

    if (isNullOrUndefined(options.ignoreInitial)) {
        options.ignoreInitial = true;
    }

    watcher = chokidar.watch(glob, options);

    if (task) {
        fn = function fn() {
            task(emptyFunction);
        };

        watcher
            .on("change", fn)
            .on("unlink", fn)
            .on("add", fn);
    }

    return watcher;
}
